/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package editor_textos.Gui;

import editor_textos.ControladorDocumento.ControladorDocumentos;
import editor_textos.controlador_editor;
import editor_textos.Editor;
import editor_textos.Documento;
import javax.swing.JFrame;


/**
 *
 * @author Dario R
 */
public class FrmNotas extends javax.swing.JFrame {
    ControladorDocumentos controlador;
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FrmNotas.class.getName());

    /**
     * Creates new form FrmNotas
     */
    public FrmNotas() {
        initComponents();
        controlador = new ControladorDocumentos(new Documento());
        this.setExtendedState(JFrame.MAXIMIZED_BOTH);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jCheckBoxMenuItem6 = new javax.swing.JCheckBoxMenuItem();
        DskpNotas = new javax.swing.JDesktopPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        TaNota = new javax.swing.JTextArea();
        jMenuBar1 = new javax.swing.JMenuBar();
        MArchivo = new javax.swing.JMenu();
        MitAbrir = new javax.swing.JMenuItem();
        MitGuardar = new javax.swing.JMenuItem();
        MitSalir = new javax.swing.JMenuItem();
        MEditar = new javax.swing.JMenu();
        ItemCopiar = new javax.swing.JMenuItem();
        ItemCortar = new javax.swing.JMenuItem();
        ItemPegar = new javax.swing.JMenuItem();
        CbxNegrita = new javax.swing.JCheckBoxMenuItem();
        CboxCursiva = new javax.swing.JCheckBoxMenuItem();
        ItemCambiarFondo = new javax.swing.JMenuItem();
        ItemColorLetra = new javax.swing.JMenuItem();

        jCheckBoxMenuItem6.setSelected(true);
        jCheckBoxMenuItem6.setText("jCheckBoxMenuItem6");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        TaNota.setColumns(20);
        TaNota.setRows(5);
        jScrollPane1.setViewportView(TaNota);

        DskpNotas.setLayer(jScrollPane1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout DskpNotasLayout = new javax.swing.GroupLayout(DskpNotas);
        DskpNotas.setLayout(DskpNotasLayout);
        DskpNotasLayout.setHorizontalGroup(
            DskpNotasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
        );
        DskpNotasLayout.setVerticalGroup(
            DskpNotasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 277, Short.MAX_VALUE)
        );

        MArchivo.setText("Archivo");

        MitAbrir.setText("Abrir Archivo");
        MitAbrir.addActionListener(this::MitAbrirActionPerformed);
        MArchivo.add(MitAbrir);

        MitGuardar.setText("Guardar");
        MitGuardar.addActionListener(this::MitGuardarActionPerformed);
        MArchivo.add(MitGuardar);

        MitSalir.setText("Salir");
        MitSalir.addActionListener(this::MitSalirActionPerformed);
        MArchivo.add(MitSalir);

        jMenuBar1.add(MArchivo);

        MEditar.setText("Editar");

        ItemCopiar.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        ItemCopiar.setText("Copiar");
        ItemCopiar.addActionListener(this::ItemCopiarActionPerformed);
        MEditar.add(ItemCopiar);

        ItemCortar.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_X, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        ItemCortar.setText("Cortar");
        ItemCortar.addActionListener(this::ItemCortarActionPerformed);
        MEditar.add(ItemCortar);

        ItemPegar.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_V, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        ItemPegar.setText("Pegar");
        ItemPegar.addActionListener(this::ItemPegarActionPerformed);
        MEditar.add(ItemPegar);

        CbxNegrita.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_B, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        CbxNegrita.setSelected(true);
        CbxNegrita.setText("Negrita");
        CbxNegrita.addActionListener(this::CbxNegritaActionPerformed);
        MEditar.add(CbxNegrita);

        CboxCursiva.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_K, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        CboxCursiva.setSelected(true);
        CboxCursiva.setText("Fuente Cursiva");
        CboxCursiva.addActionListener(this::CboxCursivaActionPerformed);
        MEditar.add(CboxCursiva);

        ItemCambiarFondo.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F, java.awt.event.InputEvent.ALT_DOWN_MASK));
        ItemCambiarFondo.setText("Cambiar color fondo");
        ItemCambiarFondo.addActionListener(this::ItemCambiarFondoActionPerformed);
        MEditar.add(ItemCambiarFondo);

        ItemColorLetra.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_O, java.awt.event.InputEvent.ALT_DOWN_MASK));
        ItemColorLetra.setText("Color de letra");
        ItemColorLetra.addActionListener(this::ItemColorLetraActionPerformed);
        MEditar.add(ItemColorLetra);

        jMenuBar1.add(MEditar);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(DskpNotas)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(DskpNotas)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void MitSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MitSalirActionPerformed
        dispose();
    }//GEN-LAST:event_MitSalirActionPerformed

    private void MitAbrirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MitAbrirActionPerformed
        controlador.abrirArchivo();
        TaNota.setText(controlador.getDocumentos().getContenido());
        
    }//GEN-LAST:event_MitAbrirActionPerformed

    private void MitGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MitGuardarActionPerformed
        controlador.getDocumentos().setContenido(TaNota.getText());

        controlador.guardarArchivo();
    }//GEN-LAST:event_MitGuardarActionPerformed

    private void CboxCursivaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CboxCursivaActionPerformed
    int estilo = 0;

    if (CbxNegrita.isSelected()) {
        estilo = estilo + 1;
    }

    if (CboxCursiva.isSelected()) {
        estilo = estilo + 2;
    }

    TaNota.setFont(new java.awt.Font("Arial", estilo, 12));   
    }//GEN-LAST:event_CboxCursivaActionPerformed

    private void ItemCopiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ItemCopiarActionPerformed
        TaNota.copy();
    }//GEN-LAST:event_ItemCopiarActionPerformed

    private void ItemCortarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ItemCortarActionPerformed
        TaNota.cut();
    }//GEN-LAST:event_ItemCortarActionPerformed

    private void ItemPegarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ItemPegarActionPerformed
        TaNota.paste();
    }//GEN-LAST:event_ItemPegarActionPerformed

    private void CbxNegritaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CbxNegritaActionPerformed
     int estilo = 0;
     if (CbxNegrita.isSelected()) {
        estilo = estilo + 1;
     }
     if (CboxCursiva.isSelected()) {
        estilo = estilo + 2;
    }
     TaNota.setFont(new java.awt.Font("Arial", estilo, 12));
    }//GEN-LAST:event_CbxNegritaActionPerformed

    private void ItemCambiarFondoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ItemCambiarFondoActionPerformed
         java.awt.Color color = javax.swing.JColorChooser.showDialog(
            this,
            "Seleccione un color",
            TaNota.getBackground());
         if (color != null) {
        TaNota.setBackground(color);
         } 
    }//GEN-LAST:event_ItemCambiarFondoActionPerformed

    private void ItemColorLetraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ItemColorLetraActionPerformed
        java.awt.Color color = javax.swing.JColorChooser.showDialog(
            this,
            "Seleccione un color",
            TaNota.getForeground());
        if (color != null) {
        TaNota.setForeground(color);
        }
    }//GEN-LAST:event_ItemColorLetraActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new FrmNotas().setVisible(true));
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBoxMenuItem CboxCursiva;
    private javax.swing.JCheckBoxMenuItem CbxNegrita;
    private javax.swing.JDesktopPane DskpNotas;
    private javax.swing.JMenuItem ItemCambiarFondo;
    private javax.swing.JMenuItem ItemColorLetra;
    private javax.swing.JMenuItem ItemCopiar;
    private javax.swing.JMenuItem ItemCortar;
    private javax.swing.JMenuItem ItemPegar;
    private javax.swing.JMenu MArchivo;
    private javax.swing.JMenu MEditar;
    private javax.swing.JMenuItem MitAbrir;
    private javax.swing.JMenuItem MitGuardar;
    private javax.swing.JMenuItem MitSalir;
    private javax.swing.JTextArea TaNota;
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItem6;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
